---
title: "The Exchange Rate Volatility and Tourism in Turkey"
author: "Rohat Alp"
date: "3/05/2019"
output: md_document
---

The paper has written during the last semestre of my senior year as a graduation thesis. The topic itself is deeply related to my previous experiences and the the data that has been used can be found the **link** below.

 (https://evds2.tcmb.gov.tr)

## Abstract 

This paper investigates the relationship between the average expenditure per tourist which is calculated as total travel incomes   divided by the total number of departing visitors, the exchange rate and inflation of package holidays by using OLS method. The    analysis has covered the period of 2005 – 2018 on a monthly basis. The empirical results have stated that the exchange rate        volatility and the inflation of package holidays have a negative and statistically significant effect on the average expenditure   per tourist.


Here is the [thesis](https://alprohat.netlify.com/thesis/thesis.pdf).


